config/routes.rb
Tessle::Application.routes.draw do
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  devise_scope :user do
    get "login", to: 'devise/sessions#new'
    get "signup", to: "devise/registrations#new"
    delete "signout", to: 'devise/sessions#destroy'
    post 'users/avatar' => 'registrations#update_avatar'
  end

  resources :users do
    member do
      get :private, to: "private_messages#private"
      get :following, :followers
      get :tags
      get :chatted
      get :private_chat, to: "private_messages#private_chat"
      get :remove_chat, to: 'private_messages#remove_chat'
    end
  end
  
  get "posts/tags" => "posts#tags", as: :tags
  post "posts/preview" => "posts#preview"
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do #, only: [:index, :new, :show, :create, :destroy] do
    resources :messages
    member do
      get :chat, to: "messages#chat"
    end
  end

  resources :messages
  resources :private_messages

  resources :user_relationships, only: [:create, :destroy]
  resources :tessle_relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  post 'pusher/auth'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div id="main_error_alert" class="alert alert-error">
    <a class="close" id="close_error" href="javascript: void(0);" onclick="document.getElementById('main_error_alert').style.display = 'none';">&times;</a>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ul class="posts list-style">
  <!-- This causes render to use given partial to render each element in collection -->
  <%= render partial: 'shared/feed_item', collection: @feed_items %>
</ul>

<div id="append_and_paginate" class="center">
  <%= will_paginate @feed_items %>
</div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= "post#{feed_item.id}" %>">
  <% if user_signed_in? && (current_user.following_user?(feed_item.user) || current_user?(feed_item.user)) %>
    <div class="follow-post-block post-block">
  <% else %>
    <div class="no-follow-post-block post-block">
  <% end %>

    <div class="post-image-header">
      <div class="post-image-block">
        <span class="image_placeholder">
            <%= image_tag feed_item.image_url(:thumb) %>
        </span>
      </div>
      <div class="post-header-block">
        <div><p><%= Pusher.get("/channels/presence-post-#{feed_item.id}", {:info => "user_count"})[:user_count] %> active</p></div>
        <div><p>Posted <%= time_ago_in_words(feed_item.created_at) %> ago</p></div>
        <div><p><span id="post-user"><%= link_to feed_item.user.user_name, feed_item.user %></span></p></div>
      </div>
    </div>

    <div class="post-title"><a href="<%= if feed_item.url.blank? then feed_item.image_url else feed_item.url end %>" target="_blank"><%= feed_item.title %></a></div>
    <div class="post-chat-block">
      <%= link_to("", [:chat, feed_item], title: "chat", class: "diamond", remote: true) %>
    </div>
    <span class="chatted-number"><%= feed_item.votes_for %> chatted</span>

    <div class="post-tessles hidden-phone">
      <span class="post-tessles-commas"><%= raw feed_item.tag_list.map {|t| link_to t, tag_path(t)}.join(' ') %></span>
    </div>

    <ul class="post-button-block pull-right">
      <li class="post-button">
        <%= link_to "", feed_item, class: "post-button-link" %>
      </li>
    </ul>
  </div >
</li>

app/views/shared/_other_user_buttons.html.erb
<ul class="user_menu_buttons list-style">
  <li>
  <%= render 'users/follow_form' %>
  </li>
  <li>
  <%= link_to 'Message', private_chat_user_path(@user), remote: true %>
  </li>
</ul>

app/views/shared/_stats.html.erb
<% @user ||= current_user # ||= assigns current_user if @user is nil, otherwise keeps @user the same %>
<section class="stats">
  <div class="stat-element">
    <center>
      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          <%= @user.followed_users.count %>
        </strong>
        <span style="display: block">following</span>
      </a>
    </center>
  </div>
  <div class="stat-element">
    <center>
      <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
        <span style="display: block">followers</span>
      </a>
    </center>
  </div>
</section>
<section class="stats" style="margin-bottom:5%;">
  <div class="stat-element">
    <center>
      <a href="<%= tags_user_path(@user) %>">
        <strong id="tessles" class="stat">
          <%= @user.tags.count %>
        </strong>
        <span style="display: block">tags</span>
      </a>
    </center>
  </div>
  <div class="stat-element">
    <center>
      <a href="<%= user_path(@user) %>">
        <strong id="posts" class="stat">
          <%= @user.posts.count %>
        </strong>
        <span style="display: block">posts</span>
      </a>
    </center>
  </div>
</section>

app/views/shared/_user_buttons.html.erb
<ul class="user_menu_buttons list-style">
  <li>
  <%= link_to "Create New Post", new_post_path,  method: "get", id: "create_post_btn" %>
  </li>
  <li>
  <%= link_to "Edit User Settings", edit_user_registration_path, method: "get", id: "edit_user_settings_btn" %>
  </li>
</ul>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>
<center>
<a href="<%= user_path(@user) %>">
  <%= image_tag @user.avatar.url(:thumb), class: "img-circle", width: 100, height: 100, style: "margin-bottom: 10px;" %>
</a>
<h1 class="center">
  <%= link_to @user.user_name, @user, class: "user_link" %>
  <% if Pusher.get("/channels/private-#{@user.id}")[:occupied] %>
    <div class="online_circle"></div>
  <% end %>
</h1>
<% if @user.admin? %>
  <!-- <span id="admin_user" class="center">Administrator</span> -->
<% end %>
<span id="user_credits" class="center">Coins: <%= @user.karma %></span>
</center>