config/routes.rb
Tessle::Application.routes.draw do
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  devise_scope :user do
    get "login", to: 'devise/sessions#new'
    get "signup", to: "devise/registrations#new"
    delete "signout", to: 'devise/sessions#destroy'
    post 'users/avatar' => 'registrations#update_avatar'
  end

  resources :users do
    member do
      get :private, to: "private_messages#private"
      get :following, :followers
      get :tags
      get :chatted
      get :private_chat, to: "private_messages#private_chat"
      get :remove_chat, to: 'private_messages#remove_chat'
    end
  end
  
  get "posts/tags" => "posts#tags", as: :tags
  post "posts/preview" => "posts#preview"
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do #, only: [:index, :new, :show, :create, :destroy] do
    resources :messages
    member do
      get :chat, to: "messages#chat"
    end
  end

  resources :messages
  resources :private_messages

  resources :user_relationships, only: [:create, :destroy]
  resources :tessle_relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  post 'pusher/auth'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url, :score, :tag_list, :image, :remote_image_url, :direct_upload_url
  belongs_to :user
  has_many :messages, as: :messageable, dependent: :destroy

  mount_uploader :image, ImageUploader
  # process_in_background :image # Used for carrierwave_backgrounder

  acts_as_taggable_on :tags
  acts_as_voteable
  is_impressionable

  validates :title, presence: true, length: { maximum: 70 }
  validates :user_id, presence: true
  validates :tag_list, presence: true
  validate :maximum_amount_of_tags
  validate :validate_image_fields

  # default_scope order: 'posts.score DESC'

  # ActiveRecord Callbacks
  after_find :calculate_score
  # before_create :default_values

  # Calculates new Gem score, might need to be optimized
  def calculate_score
    unless self.new_record?
      # ScoringPostsWorker.perform_async(self)
      # time_elapsed  = (Time.zone.now - self.created_at) / 3600
      # score = (self.votes_for) / ((time_elapsed + 2) ** (1.5))

      time_elapsed  = 1440 - ((Time.zone.now - self.created_at) / 60)
      score = (self.votes_for * 20) + time_elapsed
      self.update_attribute(:score, score)
    end
  end


  include PgSearch
  pg_search_scope :search, against: [:title],
    using: {tsearch: {dictionary: "english"}},
    associated_against: {tags: [:name]}

  scope :top_ten,
    select("posts.id, posts.title, posts.created_at, count(messages.id) AS messages_count").where("posts.created_at > ?", 3.days.ago).joins(:messages).group("posts.id").order("messages_count DESC").limit(10)


  # Search functionality
  # include PgSearch
  # pg_search_scope :search, against: [:title],
  #   using: {tsearch: {dictionary: "english"}},
  #   associated_against: {tags: [:name]}
  # def self.text_search(query)
  #   if query.present?
  #     search(query)
  #   else
  #     scoped
  #   end
  # end

  def to_param
    "#{id}-#{title}".parameterize
  end

  # Returns posts from the users being followed by the given user.
  # SELECT * FROM posts WHERE user_id IN (SELECT followed_id FROM post_relationships WHERE follower_id = 1) R user_id = 1
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM user_relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end

  def self.from_tags_tessled_by(user)
    taggable_ids = "SELECT t.taggable_id FROM tessle_relationships AS tr, taggings AS t WHERE tr.user_id = :user_id AND t.tag_id = tr.tag_id"
    followed_user_ids = "SELECT followed_id FROM user_relationships
                         WHERE follower_id = :user_id"

    where("id IN (#{taggable_ids}) OR user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)

  end


  # Returns chatted posts from the user
  def self.from_user_chatted_by(user)
    where("posts.id = votes.voteable_id AND votes.voter_id = :user_id", user_id: user.id).joins(:votes).group("posts.id, votes.id").order("votes.id DESC")
  end


  def maximum_amount_of_tags
    number_of_tags = tag_list_cache_on("tags").uniq.length
    errors.add(:base, "Please only use up to 5 tessles") if number_of_tags > 5
  end

  # def url_or_image
  #   errors.add(:base, "Please only use url or an uploaded image, not both") if ( !remote_image_url.blank? and !image.blank?)
  # end

  def validate_image_fields
    if remote_image_url.present?
       # condition/validations for the url
    elsif image
       # condition/validations for uploaded image
    else
       errors.add(:base, "No image url or local image provided")
    end
  end

  def add_tags=(args)
    return if !args.is_a?(Hash)
    list = args[:tag_list]
    list.gsub!(/<<<(.+?)>>>/) { ActsAsTaggableOn::Tag.find_or_create_by_name(name: $1).name } if list
  end

  def parse_tag_list(list)
    self.tag_list = list
  end

  # private
  #   def default_values
  #     self.score ||= 1440
  #   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]
  before_filter :correct_user, only: [ :edit, :update, :destroy]
  before_filter :admin_user, only: []
  impressionist actions: [:show]

  def show
    @messageable_id = params[:id].to_i
    @messageable_type_lower = 'post'

    @post = Post.find(@messageable_id)
    # @top_messages = Message.top_messages(@messageable_id, 10)
    @past_messages = Message.previous_10(@messageable_id, 'Post').reverse

    CalcScoreWorker.perform_async(@messageable_id, 'Post')
    if user_signed_in?
      TessleWorker.perform_async(@messageable_id, current_user.id)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(params[:post])
    @post.add_tags={:tag_list => params[:post][:tag_list]}
    @post.parse_tag_list(params[:post][:tag_list])

    if @post.save
      CalcScoreWorker.perform_async(@post.id, 'Post')
      TessleWorker.perform_async(@post.id, current_user.id)

      if params[:post][:direct_upload_url].present?
        CarrierwaveImageWorker.perform_async(@post.id, params[:post][:direct_upload_url])
        flash[:notice] = "Processing post image..."
      else
        flash[:success] = "Your post has been successfully created!"
      end
      
      redirect_to current_user
    else
      # render 'new'
      redirect_to root_url
    end
  end

  def index
    if params[:tag]
      @title = params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page])
      @past_messages = Message.previous_10(@messageable_id, 'Tag').reverse

      # Need to think about how to handle empty case
      @messageable_id = params[:id].to_i
      @messageable_type_lower = 'tag'
    else
      @title = "All Posts"
      # @posts = Post.text_search(params[:query]).paginate(page: params[:page])
      @posts = Post.all.paginate(page: params[:page])
    end
  end


  # Use these if you want to allow users to edit posts.
  # def edit
  # end

  # def update
  # end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post removed!"
    redirect_to current_user
  end

  def tags
    respond_to do |format|
      format.json{ render :json => tag_tokens(params[:q]) }
    end
  end

  def preview
    param_url = params[:url]
    doc = Nokogiri::HTML(open(param_url), nil, 'UTF-8')

    title = ""
    url = ""
    image_url = ""

    doc.xpath("//head//meta").each do |meta|
      if meta['property'] == 'og:title'
        title = meta['content']
      elsif meta['property'] == 'og:url'
        url = meta['content']
      elsif meta['property'] == 'og:image'
        image_url = meta['content']
      end
    end

    if title == ""
      title_node = doc.at_xpath("//head//title")
      if title_node
        title = title_node.text
      elsif doc.title
        title = doc.title
      else
        title = param_url
      end
    end


    if url == ""
      url = param_url
    end

    # Used for imgur thumbnail
    if url =~ /i.imgur/
      p_index = url.rindex(".")
      image_url = url[0..p_index-1] + "s" + url[p_index..-1]
    end
    
    render :json => {:title => title, :url => url, :image_url => image_url} and return

    if url =~ /i.imgur/
      p_index = url.rindex(".")
      image_url = url[0..p_index-1] + "s" + url[p_index..-1]
    end

    render :json => {:title => title, :url => url, :image_url => image_url} and return

  end

  private
    def correct_user
      unless current_user.admin?
        @post = current_user.posts.find_by_id(params[:id].to_i)
        redirect_to root_url if @post.nil?
      end
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/views/posts/_direct_upload_form.html.erb
<%= s3_uploader_form callback_method: "PUT", callback_param: "post[image_url]", id: "post-s3-uploader" do %>
  <%= file_field_tag :file, multiple: false, class: 'hidden' %>
<% end %>

app/views/posts/_form.html.erb
<div class="new-post" id="create-post">
  <div class="new-post-inner">
    <%= simple_form_for @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="new-title-description">
      <%= f.input :title, placeholder: "Create a post...",
      input_html: { :id => "post_title", autocomplete: 'off' }, label: false, error: false %>
    </div>

    <div class="tab-content">
      <%= f.input :tag_list,label: false,
    placeholder: "Tags: Funny, Cat, Videos",
    input_html: { "data-load" => @post.tags.map(&:attributes).to_json,
      :id => "post_tessles" }, error: false %>
      <div class="tab-pane active" id="link">
        <%= f.input :url, placeholder: "Add a link", input_html: { :id => "post_url" }, label: false, error: false %>
      </div>

      <div class="tab-pane" id="photo">
        <%= f.file_field :image, label: "Upload a picture", error: false, onchange: "readLocalURL(this);" %>
        <div id="upload_file_wrapper">
        <a href="javascript: void(0);" onclick="document.getElementById('file').click(); return false;" class="button" id="upload_file">Upload File</a>
        <div id="posts_container"></div>
        <script id="template-upload" type="text/x-tmpl">
        <div id="file-{%=o.unique_id%}" class="upload">
        {%=o.name%}
        <div class="progress"><div class="bar" style="width: 0%"></div></div>
        </div>
        </script>
      </div>
        <%= f.hidden_field :remote_image_url, error: false %>
        <%= f.hidden_field :direct_upload_url, error: false %>
      </div>

      <div class="tab-pane" id="text">
      </div>
    </div>

    <div id="preview_img"></div>

      <%= submit_tag 'Clear', type: :reset, class: "cancel" %>
      <%= f.button :submit, "Post", id: "new_post_button" %>

      <% end %>

      <%= render partial: "posts/direct_upload_form" %>
    </div>
  </div>

app/views/posts/_post.html.erb
<li id="<%= "post#{post.id}" %>">
  <% if user_signed_in? && (current_user.following_user?(post.user) || current_user?(post.user)) %>
    <div class="follow-post-block post-block">
  <% else %>
    <div class="no-follow-post-block post-block">
  <% end %>

    <div class="post-image-header">
      <div class="post-image-block">
        <span class="image_placeholder">
            <%= image_tag post.image_url(:thumb), class: "img-circle" %>
        </span>
      </div>
      <div class="post-header-block">
        <div><p><%= Pusher.get("/channels/presence-post-#{post.id}", {:info => "user_count"})[:user_count] %> active</p></div>
        <div><p>Posted <%= time_ago_in_words(post.created_at) %> ago</p></div>
        <div><p><span id="post-user"><%= link_to post.user.user_name, post.user %></span></p></div>
      </div>
    </div>

    <span class="post-title"><a href="<%= if post.url.blank? then post.image_url else post.url end %>" target="_blank"><%= post.title %></a></span>

    <div class="post-chat-block">
      <% if signed_in? %>
        <%= link_to "", post, title: "chat", class: "post-chat-link diamond" %>
      <% else %>
        <%= link_to "", signup_path, title: "chat", class: "post-chat-link diamond" %>
      <% end %>
    </div>
    <span class="chatted-number"><%= post.votes_for %> chatted</span>


    <div class="post-tessles hidden-phone">
      <span class="post-tessles-commas"><%= raw post.tag_list.map {|t| link_to t, tag_path(t)}.join(' ') %></span>
    </div>

    <ul class="post-button-block pull-right">
      <li class="post-button">
        <%= link_to "", post, class: "post-button-link" %>
      </li>
      <% if user_signed_in? and current_user?(post.user) or current_user.try(:admin?) %>
      <li class="post-button post-delete-button">
        <%= link_to "delete", post, method: :delete, data: { confirm: "Are you sure?" }, class: "post-delete-link" %>
      </li>
      <% end %>
    </ul>
  </div >
</li>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<% if params[:query].blank? %>
<% provide(:title, @title) %>
<% else %>
<% provide(:title, params[:query]) %>
<h1>Results for <i><%= params[:query] %></i>...</h1>
<% end %>

<ul class="posts list-style">
  <%= render @posts %>
</ul>

<div id="append_and_paginate" class="center">
  <%= will_paginate @posts %>
</div>
</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<!-- Runs when /posts/1/ is accessed -->
<% provide(:title, @post.title) %>

<div class="row">
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-8">
        <ul class="posts">
          <li id="<%= "post#{@post.id}" %>">
            <% if signed_in? && (current_user.following_user?(@post.user) || current_user?(@post.user)) %>
              <div class="follow-post-block post-block">
            <% else %>
              <div class="no-follow-post-block post-block">
            <% end %>
              <div class="post-image-header">
                <div class="post-image-block">
                  <span class="image_placeholder">
                      <%= image_tag @post.image_url(:thumb) %>
                  </span>
                </div>
                <div class="post-header-block">
                  <div><p><%= @post.votes_for %> chatted | <%= Pusher.get("/channels/presence-post-#{@post.id}", {:info => "user_count"})[:user_count] %> active</p></div>
                  <div><p>Posted <%= time_ago_in_words(@post.created_at) %> ago</p></div>
                  <div><p><span id="post-user"><%= link_to @post.user.user_name, @post.user %></span></p></div>
                </div>
              </div>

              <div class="post-title"><a href="<%= if @post.url.blank? then @post.image_url else @post.url end %>" target="_blank"><%= @post.title %></a></div>

              <div class="post-tessles">
                <%= raw @post.tag_list.map {|t| link_to t, tag_path(t)}.join(' ') %>
              </div>
            </div >
          </li>
        </ul>

      </div>

      <div class="col-md-4" id="show-mid-span">
        <div class="white_box" id="stats-box">
          <h2 class="h2-fix" id="stats-header">Stats</h2>
          <section class="stats">
            <div class="stat-element">
              <center>
                <div class="show-stats-number"><%= @post.votes_for %></div>
                <div class="show-stats-description">chatted</div>
              </center>
            </div>
            <div class="stat-element">
              <center>
                <div class="show-stats-number"><%= @post.messages.count %></div>
                <div class="show-stats-description">messages</div>
              </center>
            </div>
          </section>
          <section class="stats">
            <div class="stat-element">
              <center>
                <div class="show-stats-number"><%= @post.impressionist_count(:filter=>:ip_address) %></div>
                <div class="show-stats-description">views</div>
              </center>
            </div>
            <div class="stat-element">
              <center>
                <div class="show-stats-number"><%= active_num = Pusher.get("/channels/presence-post-#{@post.id}", {:info => "user_count"})[:user_count] %></div>
                <div class="show-stats-description">active</div>
              </center>
            </div>
          </section>
        </div>

        <div class="white_box" id="current-users">
          <% if active_num > 0 %>
            <% if user_signed_in? %>
            <h2 class="h2-fix">Online Users</h2>
            <ul class="online-users" id="online-users"></ul>
            <% else %>
            <h2 class="h2-fix">Please sign in for chats!</h2>
            <% end %>
          <% end %>
        </div>


      </div>
    </div>

    </div>
    <% if user_signed_in? %>
    <div class="col-md-4" id="side-span">
      <%= render partial: 'messages/side_chat' %>
    </div>
    <script>
      $(function (){
        var postChannel = socket.subscribe("presence-post-<%= @messageable_id %>");
        var myDiv = document.getElementById("side-chat-body");
        var current_user_id = "<%= current_user.id %>"

        postChannel.bind('new_<%= @messageable_type_lower %>_message', function(data) {
          var post_chat_id = $('#new_<%= @messageable_type_lower %>_chat' + data.id);
          if(post_chat_id.length && (data.sender_id != current_user_id)) {
            post_chat_id.append(data.html);
            myDiv.scrollTop = myDiv.scrollHeight;
          }
        });

        bindChatForm('<%= @messageable_id %>', '<%= @messageable_type_lower %>');
        myDiv.scrollTop = myDiv.scrollHeight;

      });
    </script>
    <% end %>
  </div>